<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bfc3b422-1dc9-4d25-846f-4d27b20cfca4</testSuiteGuid>
   <testCaseLink>
      <guid>9e7d7634-5197-434c-bb53-a4b32e83227e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RestAPI/TC_CreateOrder</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ca288153-c2db-44aa-a6e7-faf194569425</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Orders</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ca288153-c2db-44aa-a6e7-faf194569425</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>c7f71826-1921-4987-90fe-1e2f488b049a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ca288153-c2db-44aa-a6e7-faf194569425</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>amount</value>
         <variableId>a8d2a2f7-6a2d-41d0-a9e7-1c35dcf21b07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ca288153-c2db-44aa-a6e7-faf194569425</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>currency</value>
         <variableId>4826021c-9c75-49df-b3d6-f0e0c9b6e4e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ca288153-c2db-44aa-a6e7-faf194569425</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>ea1d2f8e-83a1-478b-aaee-099ba2e804cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d65b0430-168d-461f-91fb-357c8e2a7791</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RestAPI/TC_GetOrder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b63240f-ab2e-448b-9c3a-f83fae908d36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6302cb6-cd7f-486d-9f21-fb0858f0a881</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f45ddf5-f626-4551-a78e-b36a67bfb6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be1c0074-ba1c-44c6-bd4c-29f65580202f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
