<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload files_qqfile</name>
   <tag></tag>
   <elementGuidId>615afd06-a91e-4867-a17d-b6b32690f2b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>c</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;qqfile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9cbb025-89e1-4626-8290-1ce97c6dabb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>qq-button-id</name>
      <type>Main</type>
      <value>cb4ea59d-5099-4962-b0b7-fb0ea2ae1993</value>
      <webElementGuid>8cd2d594-2971-4b65-a4fe-b3dd0b79c600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>file input</value>
      <webElementGuid>a6eb5232-e996-4ef2-968e-448b0c64d452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>b6070c34-2009-4c75-8aea-4d84cc7e8486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qqfile</value>
      <webElementGuid>3a48c917-044f-4e18-bbfb-05d5470f021a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fine-uploader-gallery&quot;)/div[@class=&quot;qq-uploader-selector qq-uploader qq-gallery&quot;]/div[@class=&quot;qq-upload-button-selector qq-upload-button qq-upload-button-hover&quot;]/input[1]</value>
      <webElementGuid>4edfaad6-5bd7-47f4-b266-15753c026280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='qqfile']</value>
      <webElementGuid>849fae2d-094d-48d8-938e-9bef941f67a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fine-uploader-gallery']/div/div[3]/input</value>
      <webElementGuid>f1069226-6251-4e0b-a2da-7ac3fca975b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b30614be-e21b-410f-887e-d2fd370cc489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'file input' and @type = 'file' and @name = 'qqfile']</value>
      <webElementGuid>db923598-440f-4640-99b3-0a2516c05749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
